# Generated by Django 3.0.5 on 2020-05-11 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug_reporter', '0002_auto_20200511_0716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='user',
            new_name='creator',
        ),
    ]
