# Generated by Django 3.0.5 on 2020-05-17 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bug_reporter', '0004_auto_20200517_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bug',
            options={'ordering': ['issued_at']},
        ),
        migrations.AddField(
            model_name='bug',
            name='assign_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues_assigned_to_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
