# Generated by Django 3.0.5 on 2020-04-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_reporter', '0005_auto_20200425_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='file',
        ),
        migrations.AddField(
            model_name='bug',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='uploaded image'),
        ),
        migrations.AddField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('R', 'Resolved'), ('T', 'To be Discussed')], default='pending', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bug',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
