# Generated by Django 3.0.5 on 2020-04-25 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug_reporter', '0006_auto_20200425_1906'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
