# Generated by Django 3.0.5 on 2020-05-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_reporter', '0006_auto_20200517_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='githublink',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
