# Generated by Django 3.0.5 on 2020-05-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_reporter', '0008_auto_20200518_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='domain',
            field=models.CharField(blank=True, choices=[('f', 'frontend'), ('b', 'backend')], max_length=100, null=True),
        ),
    ]
