# Generated by Django 3.0.5 on 2020-04-27 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug_reporter', '0008_auto_20200427_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user',
            new_name='users',
        ),
    ]
