# Generated by Django 3.0.5 on 2020-04-27 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bug_reporter', '0009_auto_20200427_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='bug_reporter.Project'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='bug_reporter.User'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='bug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bug_reporter.Bug'),
        ),
    ]
