# Generated by Django 3.0.5 on 2020-05-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_reporter', '0009_bug_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='domain',
            field=models.CharField(blank=True, choices=[('f', 'frontend'), ('b', 'backend'), ('o', 'other')], max_length=100, null=True),
        ),
    ]
