# Generated by Django 3.0.5 on 2020-05-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_reporter', '0010_auto_20200520_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
