# Generated by Django 3.0.5 on 2020-04-28 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bug_reporter', '0011_auto_20200428_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='bug',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bug_reporter.Bug'),
        ),
    ]
