# Generated by Django 3.0.5 on 2020-05-21 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug_reporter', '0011_auto_20200520_1205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
