# Generated by Django 3.0.5 on 2020-05-21 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug_reporter', '0012_delete_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='bug',
            name='status',
        ),
    ]
