# Generated by Django 3.0.6 on 2020-05-28 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_reporter', '0014_auto_20200521_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebookLink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='instagramLink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='socialEmail',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='githublink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
