# Generated by Django 3.0.6 on 2020-05-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_reporter', '0015_auto_20200528_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linkedinLink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
