# Generated by Django 3.0.6 on 2020-05-30 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bug_reporter', '0017_auto_20200528_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues_assigned_to_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
