# Generated by Django 3.0.6 on 2020-05-30 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bug_reporter', '0019_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='bug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bug_reporter.Bug'),
        ),
    ]
