# Generated by Django 3.0.6 on 2020-05-30 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug_reporter', '0020_auto_20200530_0714'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
