# Generated by Django 3.0.6 on 2020-05-31 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug_reporter', '0021_auto_20200530_0716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='githublink',
            new_name='githubLink',
        ),
    ]
