# Generated by Django 3.0.6 on 2020-06-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_reporter', '0025_auto_20200603_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='tag',
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bug', models.ManyToManyField(blank=True, to='bug_reporter.Bug')),
            ],
        ),
    ]
